package com.example.ui.model

enum class AppLanguage(
    val code: String,
    val title: String,
    val subtitle: String,
    val flag: String,
    val shortLabel: String
) {
    FORMAL_ENGLISH(
        code = "en_formal",
        title = "Formal English",
        subtitle = "Official Business English",
        flag = "🇬🇧",
        shortLabel = "Formal EN"
    ),
    URDU(
        code = "ur",
        title = "اردو",
        subtitle = "پاکستان کی قومی زبان",
        flag = "🇵🇰",
        shortLabel = "اردو"
    ),
    ROMAN_URDU(
        code = "ur_roman",
        title = "Roman Urdu",
        subtitle = "Urdu in Roman Script",
        flag = "🔤",
        shortLabel = "Roman"
    )
}

// Localized Strings Dictionary
data class AppStrings(
    // App Top Bar & Header
    val appTagline: String,
    
    // Bottom Nav Tabs
    val navHome: String,
    val navCatalog: String,
    val navOrder: String,
    val navTrack: String,
    val navHistory: String,
    val navContact: String,
    val navAdmin: String,

    // Home Screen
    val homeWelcome: String,
    val homeSubtitle: String,
    val homePlaceOrderBtn: String,
    val homeTrackOrderBtn: String,
    val homeFeaturedTitle: String,
    val homeViewCatalog: String,
    val homeWhyChooseUs: String,
    val homeQualityTitle: String,
    val homeQualityDesc: String,
    val homeWholesaleTitle: String,
    val homeWholesaleDesc: String,
    val homeFastDeliveryTitle: String,
    val homeFastDeliveryDesc: String,
    val homeAssistanceTitle: String,
    val homeAssistanceDesc: String,

    // Place Order Screen
    val orderFormTitle: String,
    val orderFormSub: String,
    val customerNameLabel: String,
    val shopNameLabel: String,
    val mobileNumberLabel: String,
    val addressLabel: String,
    val cityLabel: String,
    val selectBlendLabel: String,
    val selectQuantitiesLabel: String,
    val size125g: String,
    val size250g: String,
    val size500g: String,
    val size1kg: String,
    val sizeCustom: String,
    val customKgPerUnitLabel: String,
    val orderSummaryTitle: String,
    val totalWeightLabel: String,
    val reviewOrderBtn: String,
    val confirmModalTitle: String,
    val submitOrderBtn: String,
    val orderSuccessToast: String,

    // Track Order & History
    val trackOrderTitle: String,
    val enterMobileOrId: String,
    val searchOrderBtn: String,
    val orderStatusNew: String,
    val orderStatusConfirmed: String,
    val orderStatusProcessing: String,
    val orderStatusOutForDelivery: String,
    val orderStatusDelivered: String,
    val orderStatusCancelled: String,

    // Products / Catalog
    val catalogTitle: String,
    val catalogSubtitle: String,
    val blendDaneydar: String,
    val blendPremium: String,
    val blendDust: String,
    val blendElaichi: String,
    val blendHotelSpecial: String,

    // Contact & Admin
    val contactTitle: String,
    val callUsBtn: String,
    val whatsappUsBtn: String,
    val adminPortalTitle: String,
    val enterPinPrompt: String
)

fun getAppStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.FORMAL_ENGLISH -> AppStrings(
            appTagline = "Quality Tea, Trusted Service",
            navHome = "Home",
            navCatalog = "Tea Catalog",
            navOrder = "Place Order",
            navTrack = "Track Order",
            navHistory = "Order History",
            navContact = "About",
            navAdmin = "Admin",

            homeWelcome = "Welcome to SK Tea",
            homeSubtitle = "Fresh Crop • 100% Pure • Airtight Sealed",
            homePlaceOrderBtn = "Place Wholesale Order",
            homeTrackOrderBtn = "Track Live Order",
            homeFeaturedTitle = "Featured Tea Blends",
            homeViewCatalog = "View Full Catalog",
            homeWhyChooseUs = "Why Partner with SK Tea?",
            homeQualityTitle = "Superior Blend Quality",
            homeQualityDesc = "Handpicked from high-altitude tea estates delivering golden liquor, rich taste, and vibrant aroma.",
            homeWholesaleTitle = "Direct Factory Wholesale Rates",
            homeWholesaleDesc = "Transparent pricing with no middlemen, ensuring maximum profitability for your retail business.",
            homeFastDeliveryTitle = "Express Nationwide Dispatch",
            homeFastDeliveryDesc = "Reliable order processing and swift transport across Lahore and all major cities in Pakistan.",
            homeAssistanceTitle = "Need Immediate Assistance?",
            homeAssistanceDesc = "Contact our sales representatives directly via WhatsApp or Phone Call.",

            orderFormTitle = "Wholesale Order Placement",
            orderFormSub = "Select your desired blend and package breakdown below.",
            customerNameLabel = "Customer Full Name *",
            shopNameLabel = "Shop / Hotel / Business Name *",
            mobileNumberLabel = "Mobile Phone Number (WhatsApp) *",
            addressLabel = "Complete Delivery Address *",
            cityLabel = "City *",
            selectBlendLabel = "Select Tea Blend *",
            selectQuantitiesLabel = "Specify Package Quantities *",
            size125g = "125 Gram Packets",
            size250g = "250 Gram Packets",
            size500g = "500 Gram Packets",
            size1kg = "1 Kilogram Packets",
            sizeCustom = "Custom Bulk Sacks",
            customKgPerUnitLabel = "Weight per Unit (Kg)",
            orderSummaryTitle = "Order Weight Summary",
            totalWeightLabel = "Total Order Weight:",
            reviewOrderBtn = "Review & Submit Order",
            confirmModalTitle = "Confirm Order Details",
            submitOrderBtn = "Confirm & Dispatch Order",
            orderSuccessToast = "Order submitted successfully!",

            trackOrderTitle = "Order Tracking System",
            enterMobileOrId = "Enter Mobile Number or Order ID",
            searchOrderBtn = "Search Order",
            orderStatusNew = "Order Received",
            orderStatusConfirmed = "Order Confirmed",
            orderStatusProcessing = "Packing & Processing",
            orderStatusOutForDelivery = "Out for Delivery",
            orderStatusDelivered = "Delivered",
            orderStatusCancelled = "Cancelled",

            catalogTitle = "SK Tea Product Catalog",
            catalogSubtitle = "Premium teas formulated for tea stalls, hotels, households, and wholesale distribution.",
            blendDaneydar = "Daneydar Special",
            blendPremium = "Premium Mixture",
            blendDust = "Karak Hotel Dust",
            blendElaichi = "Royal Elaichi Chai",
            blendHotelSpecial = "Commercial Hotel Blend",

            contactTitle = "Contact & Corporate Office",
            callUsBtn = "Call Support",
            whatsappUsBtn = "WhatsApp Sales",
            adminPortalTitle = "Admin Management Portal",
            enterPinPrompt = "Enter 4-Digit Security PIN"
        )

        AppLanguage.URDU -> AppStrings(
            appTagline = "اعلیٰ معیار کی چائے، قابلِ اعتماد سروس",
            navHome = "ہوم",
            navCatalog = "کٹلاگ",
            navOrder = "آرڈر کریں",
            navTrack = "ٹریکنگ",
            navHistory = "ہسٹری",
            navContact = "تعارف",
            navAdmin = "ایڈمن",

            homeWelcome = "ایس کے ٹی کمپنی میں خوش آمدید",
            homeSubtitle = "تازہ فصل • 100٪ خالص • ایئر ٹائٹ پیکنگ",
            homePlaceOrderBtn = "ہول سیل آرڈر بُک کریں",
            homeTrackOrderBtn = "آرڈر ٹریک کریں",
            homeFeaturedTitle = "ہماری مشہور چائے کی اقسام",
            homeViewCatalog = "مکمل کٹلاگ دیکھیں",
            homeWhyChooseUs = "ایس کے ٹی کا انتخاب کیوں کریں؟",
            homeQualityTitle = "بہترین رنگت اور خوشبو",
            homeQualityDesc = "اعلیٰ باغات سے منتخب شدہ خالص پتی جو زبردست کڑک چائے اور شاندار ذائقہ فراہم کرتی ہے۔",
            homeWholesaleTitle = "ڈائریکٹ فیکٹری ہول سیل ریٹ",
            homeWholesaleDesc = "بغیر کسی مڈل مین کے، مناسب اور ڈائریکٹ فیکٹری ریٹ پر بااعتماد فراہمی۔",
            homeFastDeliveryTitle = "پورے پاکستان میں تیز ڈیلیوری",
            homeFastDeliveryDesc = "لاہور اور پاکستان بھر کے تمام شہروں میں فوری اور باحفاظت سامان کی ترسیل۔",
            homeAssistanceTitle = "کیا آپ کو مزید معلومات چاہیے؟",
            homeAssistanceDesc = "ہمارے نمائندے سے براہِ راست واٹس ایپ یا فون پر رابطہ کریں۔",

            orderFormTitle = "ہول سیل آرڈر فارم",
            orderFormSub = "اپنی پسندیدہ چائے اور پیکٹ کی تعداد منتخب کریں۔",
            customerNameLabel = "گاہک کا مکمل نام *",
            shopNameLabel = "دوکان / ہوٹل / بزنس کا نام *",
            mobileNumberLabel = "موبائل فون نمبر (واٹس ایپ) *",
            addressLabel = "ڈیلیوری کا مکمل پتہ *",
            cityLabel = "شہر *",
            selectBlendLabel = "چائے کی قسم منتخب کریں *",
            selectQuantitiesLabel = "پیکٹ کے سائز اور تعداد منتخب کریں *",
            size125g = "125 گرام پیکٹ",
            size250g = "250 گرام پیکٹ",
            size500g = "500 گرام پیکٹ",
            size1kg = "1 کلوگرام پیکٹ",
            sizeCustom = "حسبِ ضرورت بڑا تھیلا (بورا)",
            customKgPerUnitLabel = "فی تھیلا وزن (کلوگرام)",
            orderSummaryTitle = "آرڈر کا کل وزن",
            totalWeightLabel = "کل وزن:",
            reviewOrderBtn = "آرڈر چیک کریں اور جمع کریں",
            confirmModalTitle = "آرڈر کی تصدیق کریں",
            submitOrderBtn = "تصدیق کریں اور بھیجیں",
            orderSuccessToast = "آپ کا آرڈر کامیابی سے جمع ہو گیا ہے!",

            trackOrderTitle = "آرڈر ٹریکنگ سسٹم",
            enterMobileOrId = "موبائل نمبر یا آرڈر آئی ڈی درج کریں",
            searchOrderBtn = "آرڈر تلاش کریں",
            orderStatusNew = "نیا آرڈر موصول ہوا",
            orderStatusConfirmed = "آرڈر کی تصدیق ہو گئی",
            orderStatusProcessing = "پیکنگ اور تیاری جاری ہے",
            orderStatusOutForDelivery = "ڈیلیوری کے لیے روانہ",
            orderStatusDelivered = "کامیابی سے ڈیلیور ہو گیا",
            orderStatusCancelled = "منسوخ ہو گیا",

            catalogTitle = "ایس کے ٹی چائے کٹلاگ",
            catalogSubtitle = "ہوٹلوں، چائے کے ڈھابوں اور گھروں کے لیے تیار کردہ خصوصی بلینڈز۔",
            blendDaneydar = "دانے دار سپیشل",
            blendPremium = "پریمیم مکسچر",
            blendDust = "کڑک ہوٹل ڈسٹ",
            blendElaichi = "رائل الائچی چائے",
            blendHotelSpecial = "کمرشل ہوٹل بلینڈ",

            contactTitle = "رابطہ اور دفتر",
            callUsBtn = "کال کریں",
            whatsappUsBtn = "واٹس ایپ کریں",
            adminPortalTitle = "ایڈمن پورٹل",
            enterPinPrompt = "4 ہندسوں کا پن کوڈ درج کریں"
        )

        AppLanguage.ROMAN_URDU -> AppStrings(
            appTagline = "Aala Quality Chai, Qabil-e-Aetmad Service",
            navHome = "Home",
            navCatalog = "Catalog",
            navOrder = "Order",
            navTrack = "Track",
            navHistory = "History",
            navContact = "About",
            navAdmin = "Admin",

            homeWelcome = "SK Tea Company Me KhushAamdeed",
            homeSubtitle = "Taza Fasal • 100% Khalis • Airtight Packing",
            homePlaceOrderBtn = "Wholesale Order Book Karein",
            homeTrackOrderBtn = "Live Order Track Karein",
            homeFeaturedTitle = "Mashhoor Tea Blends",
            homeViewCatalog = "Pura Catalog Dekhein",
            homeWhyChooseUs = "SK Tea Kyun Chunayein?",
            homeQualityTitle = "Aala Rangat Aur Khushboo",
            homeQualityDesc = "Behtareen baaghat se chuni hui khalis patti jo zabardast kadak chai aur mazedar zaiqa deti hai.",
            homeWholesaleTitle = "Direct Factory Wholesale Rate",
            homeWholesaleDesc = "Bina kisi middleman ke, munaseb aur direct factory rate par baa-aetmad supply.",
            homeFastDeliveryTitle = "Tez Nationwide Delivery",
            homeFastDeliveryDesc = "Lahore aur pure Pakistan ke tamam shehron me fori aur ba-hifazat delivery.",
            homeAssistanceTitle = "Madad Chahiye Ya Sawal Hai?",
            homeAssistanceDesc = "Hamare sales representative se WhatsApp ya Call par baat karein.",

            orderFormTitle = "Wholesale Order Form",
            orderFormSub = "Apni pasandida chai aur packet ki tadad neeche chunayein.",
            customerNameLabel = "Aapka Mukammal Naam *",
            shopNameLabel = "Dukan / Hotel / Business Ka Naam *",
            mobileNumberLabel = "Mobile Number (WhatsApp) *",
            addressLabel = "Delivery Ka Pura Pata *",
            cityLabel = "Shehar Ka Naam *",
            selectBlendLabel = "Chai Ki Qism Chunayein *",
            selectQuantitiesLabel = "Packet Ki Tadad Chunayein *",
            size125g = "125g Packets",
            size250g = "250g Packets",
            size500g = "500g Packets",
            size1kg = "1kg Packets",
            sizeCustom = "Custom Bulk Sacks (Bora)",
            customKgPerUnitLabel = "Weight per Sack (Kg)",
            orderSummaryTitle = "Order Weight Summary",
            totalWeightLabel = "Total Order Weight:",
            reviewOrderBtn = "Order Check & Confirm Karein",
            confirmModalTitle = "Order Details Confirm Karein",
            submitOrderBtn = "Order Send Karein",
            orderSuccessToast = "Aapka order kamyabi se submit ho gaya hai!",

            trackOrderTitle = "Order Tracking System",
            enterMobileOrId = "Mobile Number ya Order ID darj karein",
            searchOrderBtn = "Order Search Karein",
            orderStatusNew = "Naya Order Mawasool Hua",
            orderStatusConfirmed = "Order Confirm Ho Gaya",
            orderStatusProcessing = "Packing & Processing Jari Hai",
            orderStatusOutForDelivery = "Out for Delivery",
            orderStatusDelivered = "Delivered Ho Gaya",
            orderStatusCancelled = "Cancel Ho Gaya",

            catalogTitle = "SK Tea Products Catalog",
            catalogSubtitle = "Hotels, tea stalls, aur gheron ke liye behtareen chai blends.",
            blendDaneydar = "Daneydar Special",
            blendPremium = "Premium Mixture",
            blendDust = "Karak Hotel Dust",
            blendElaichi = "Royal Elaichi Chai",
            blendHotelSpecial = "Commercial Hotel Blend",

            contactTitle = "Contact & Office Info",
            callUsBtn = "Call Karein",
            whatsappUsBtn = "WhatsApp Karein",
            adminPortalTitle = "Admin Panel",
            enterPinPrompt = "4-Digit Security PIN Darj Karein"
        )
    }
}
